apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-money-transfer-server
  namespace: temporal-money-transfer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-money-transfer-server
  template:
    metadata:
      labels:
        app: temporal-money-transfer-server
    spec:
      containers:
        - name: server
          image: steveandroulakis/temporal-moneytransfer-server:latest
          imagePullPolicy: Always
          ports:
            - name: server
              containerPort: 80
            - name: metrics
              containerPort: 9090
          env:
            - name: ADDRESS
              value: steveandroulakis-test-1.sdvdw.tmprl.cloud:7233
            - name: NAMESPACE
              value: steveandroulakis-test-1.sdvdw
            - name: CERT_PATH
              value: /etc/certs/tls.crt
            - name: KEY_PATH
              value: /etc/certs/tls.key
            - name: NODE_ENV
              value: production
            - name: PORT
              value: "80"
            - name: PROMETHEUS_ADDRESS
              value: 0.0.0.0:9090
            - name: VITE_API_URL
              value:
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-key
                  key: STRIPE_SECRET_KEY
          volumeMounts:
            - mountPath: /etc/certs
              name: certs
      volumes:
        - name: certs
          secret:
            defaultMode: 420
            secretName: temporal-money-transfer-tls
