apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-money-transfer-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: temporal-money-transfer-worker
  template:
    metadata:
      labels:
        app: temporal-money-transfer-worker
        namespace: temporal-money-transfer
    spec:
      containers:
        - name: worker-workflow
          image: steveandroulakis/temporal-moneytransfer-worker:latest
          imagePullPolicy: Always
          env:
            - name: WORKER_TYPE
              value: workflow
            - name: ADDRESS
              value: helloworld.sdvdw.tmprl.cloud:7233
            - name: NAMESPACE
              value: helloworld.sdvdw
            - name: CERT_PATH
              value: /etc/certs/tls.crt
            - name: KEY_PATH
              value: /etc/certs/tls.key
            - name: NODE_ENV
              value: production
            - name: STRIPE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: stripe-secret-key
                  key: STRIPE_SECRET_KEY
          ports:
            - name: metrics
              containerPort: 9090
          volumeMounts:
            - mountPath: /etc/certs
              name: certs
      volumes:
        - name: certs
          secret:
            defaultMode: 420
            secretName: temporal-steveandroulakis-tls